embeddings {
  tensor_name: "state:01150"
  metadata_path: "01150/state\\metadata.tsv"
  tensor_path: "01150/state\\tensors.tsv"
}
embeddings {
  tensor_name: "is_holiday:01150"
  metadata_path: "01150/is_holiday\\metadata.tsv"
  tensor_path: "01150/is_holiday\\tensors.tsv"
}
embeddings {
  tensor_name: "month:01150"
  metadata_path: "01150/month\\metadata.tsv"
  tensor_path: "01150/month\\tensors.tsv"
}
